# Generated by Django 4.2.7 on 2025-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("INR", "Indian Rupee (₹)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("AUD", "Australian Dollar (A$)"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
