# Generated by Django 5.1.6 on 2025-04-16 14:48

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_category_user_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Product image",
                null=True,
                upload_to=products.models.product_image_path,
            ),
        ),
    ]
